##########################################
# RoleBinding in staging
##########################################
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-binding
  namespace: staging
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: staging
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
